import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/theComponents/NavBar";

const nunito = Nunito({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-background antialiased`}>
        <NavBar />
        <div className="w-11/12 mx-auto pt-5">{children}</div>
      </body>
    </html>
  );
}
